apiVersion: v1
kind: ConfigMap
metadata:
  name: peer-calls-config
data:
  config.yaml: |
    base_url: /test
    ice_servers:
    - urls:
      - 'stun:stun.l.google.com:19302'
      auth_type: secret
      auth_secret:
        username: test_user
        secret: test_secret
    store:
      type: redis
      redis:
        host: redis
        port: 6379
        prefix: peercalls
