apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer-calls
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: peer-calls
  template:
    metadata:
      labels:
        app.kubernetes.io/name: peer-calls
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: peer-calls-config
      containers:
      - name: peer-calls
        image: peercalls/peercalls
        imagePullPolicy: IfNotPresent
        command: ["/app/peer-calls", "-c", "/etc/peer-calls/config.yaml"]
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /probes/liveness
            port: http
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /probes/health
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1  
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: config-volume
          mountPath: /etc/peer-calls
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        lifecycle:
          preStop:
            exec:
              command:
              - sleep
              - "10"
      serviceAccountName: peer-calls
      securityContext:
        fsGroup: 1000
