apiVersion: v1
kind: Service
metadata:
  name: peer-calls
  labels:
    app.kubernetes.io/name: peer-calls
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: peer-calls
